language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
before_script:
- npm run setup
script:
- set -e
- git config --global user.email $GH_EMAIL
- git config --global user.name $GH_USERNAME
- git remote add deploy https://${GH_TOKEN}@github.com/${GH_USERNAME}/thedebate-api.git > /dev/null 2>&1
- git checkout -b staging > /dev/null 2>&1
- git pull deploy staging > /dev/null 2>&1
- git merge master > /dev/null 2>&1
- grunt
- node server.js &
- npm test
- ! 'echo "# Build Time: `date`" >> .travis.yml'
- git add -A
- git commit -m "Travis build"
- git push deploy staging > /dev/null 2>&1
- set +e
env:
  global:
  - secure: QfieBfe5S1laVfRIhHTE9io5lJ8H3JAzQwZ0ZfaDGduMZ3vt8p+m/BmdesR1b6oHjFDQhKSHi468lqFqH9PCpQbBDhcwbs7QbOHhq3FGOlTOGKmxSqcg8KyUqhZSZAPOBWOy4odj9PteoNwuZ53IdrDExHX6IuoiqEr8PrbrzlY=
  - secure: ScVmj8dEmmuiPmr1mzmiGLNlNIrfuYcYVSFXXwlyGmI+8rRimvOywND/S4PThWXyCTdt8Cfm7caiMvIm8+8n4G1OsSWQFqTMMDXuyiN58VJtS/8Mx1Z/NsVQE5uyaF+1Xu8Aaj8HbiGJlvpgRlG2u7Gch0bn7XplMdvJNxHSuYY=
  - secure: QDL9Elx+DGtXcsRO8vkYXn3SZ1bKkNK2zgRaZBnBRsMH+ze+nUxf6lxX2QXXWmm/hmSConwqlDnb3zQkmE+EKHoxZCwsZncqhid+XlHvQ1JcH9elXL6Vv+cxpYwuughN/NfHN94/sEkzXh2xfqHoBWCi7Mhbir41phNJ5Gjjrgw=
