language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
before_script:
- npm run setup
script:
- set -e
- git config --global user.email $GH_EMAIL
- git config --global user.name $GH_USERNAME
- git remote add deploy https://${GH_TOKEN}@github.com/${GH_USERNAME}/thedebate-api.git > /dev/null 2>&1
- git checkout -b staging > /dev/null 2>&1
- git pull deploy staging > /dev/null 2>&1
- git merge master > /dev/null 2>&1
- grunt
- node server.js &
- npm test
- ! 'echo "# Build Time: `date`" >> .travis.yml'
- git add -A
- git commit -m "Travis build"
- git push deploy staging > /dev/null 2>&1
- set +e
env:
  global:
  - secure: Jdi4+qeYJsldYn1gCPqxEj11a5JV0vWKs0qYX5AwnDu93r2+4kp2SgwybRVgL2tSw169JQv7i2ME8K07ZuzQY+YX4nmGQ6rPWe6q7o7vAv6prkmz1fp/8UEH02MuzMFNxlJNjTVYfcJGNB+caEKwo3DmX2iVafckCvUFLVUAz6Y=
  - secure: g2tQHStlXWnfYNiiw6gl/57D5ZPdtkBvEjdLitqPXIgTdqc+OcxdBB7iX0yqV6ZElsAhNPZdY7k8HJF7zSrx2bfaY5ivhJ5JmynFdtj5bQWhWX5q79TOpV6+QVEAKU1BHsDnC079IOYiJavJ+BRSjtwS6HRSimCVpbrvijAoBlA=
  - secure: HfqZ5SaNo7CDoknCM8TSq7DaX5LovWS1GGeUcIWoJIE9i0JSaKvRCN9FzezvUZpYW5EhC4DYdV3wEVX4eQ8dAiuukGQmxViIlpTewpL4I3MULmAz4Cw8tcOqM+Hh4Qac/E4M3n5xlgkMwp5ZlioJFswDAG/QP5T/1xoTkpDhdZ0=
